[2025-01-28 10:57:48] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-01-28 10:59:22] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-01-28 12:43:47] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-01-28 12:43:50] INFO django.server "GET / HTTP/1.1" 302 0
[2025-01-28 12:43:50] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-01-28 12:43:50] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/login.css HTTP/1.1" 200 951
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/base.css HTTP/1.1" 200 22092
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/responsive_rtl.css HTTP/1.1" 200 2544
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/rtl.css HTTP/1.1" 200 4696
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[2025-01-28 12:43:50] INFO django.server "GET /static/admin_persian/css/sahel.css HTTP/1.1" 200 303
[2025-01-28 12:43:50] INFO django.server "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[2025-01-28 12:43:50] INFO django.server "GET /static/admin_persian/fonts/sahel/Sahel.woff HTTP/1.1" 200 45376
[2025-01-28 12:43:58] WARNING django.request Not Found: /swagger/
[2025-01-28 12:43:58] WARNING django.server "GET /swagger/ HTTP/1.1" 404 2498
[2025-01-28 12:47:38] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-01-28 12:47:40] INFO django.server "GET / HTTP/1.1" 302 0
[2025-01-28 12:47:40] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-01-28 12:47:40] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-01-28 12:47:44] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/style.css HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
[2025-01-28 12:47:44] INFO django.server "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
[2025-01-28 12:47:45] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3782
[2025-01-28 12:47:45] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
[2025-01-30 16:48:32] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:46:08] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:47:58] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:48:05] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 12:48:05] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 12:48:05] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 12:48:06] INFO django.server "GET /static/admin_persian/css/sahel.css HTTP/1.1" 200 303
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2804
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/rtl.css HTTP/1.1" 200 4696
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/login.css HTTP/1.1" 200 951
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/base.css HTTP/1.1" 200 22092
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/responsive_rtl.css HTTP/1.1" 200 2544
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/css/responsive.css HTTP/1.1" 200 17972
[2025-02-01 12:48:06] INFO django.server "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
[2025-02-01 12:48:06] INFO django.server "GET /static/admin_persian/fonts/sahel/Sahel.woff HTTP/1.1" 304 0
[2025-02-01 12:48:06] WARNING django.request Not Found: /favicon.ico
[2025-02-01 12:48:06] WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3039
[2025-02-01 12:48:18] INFO django.server "GET /swagger HTTP/1.1" 301 0
[2025-02-01 12:48:18] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
[2025-02-01 12:48:18] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
[2025-02-01 12:48:18] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3782
[2025-02-01 12:48:48] ERROR django.request Internal Server Error: /api/user-bank-info/all/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Travel-Booking-Framework\ProfilesService\Profile\api\views.py", line 97, in get
    bank_infos = UserBankInfoService.get_all_bank_infos()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UserBankInfoService' has no attribute 'get_all_bank_infos'
[2025-02-01 12:48:48] ERROR django.server "GET /api/user-bank-info/all/ HTTP/1.1" 500 22479
[2025-02-01 12:51:04] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:51:06] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 12:51:06] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 12:51:06] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 12:51:15] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 12:51:16] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3767
[2025-02-01 12:52:05] WARNING django.request Bad Request: /api/user-bank-info/
[2025-02-01 12:52:05] WARNING django.server "POST /api/user-bank-info/ HTTP/1.1" 400 100
[2025-02-01 12:52:47] ERROR django.request Internal Server Error: /api/bank-info/all/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Travel-Booking-Framework\ProfilesService\Profile\api\views.py", line 97, in get
    bank_infos = UserBankInfoService.get_all_bank_infos()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UserBankInfoService' has no attribute 'get_all_bank_infos'
[2025-02-01 12:52:47] ERROR django.server "GET /api/bank-info/all/ HTTP/1.1" 500 22459
[2025-02-01 12:55:07] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:55:09] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 12:55:09] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 12:55:09] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 12:55:12] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 12:55:12] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3767
[2025-02-01 12:55:12] INFO django.server "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
[2025-02-01 12:55:16] ERROR django.request Internal Server Error: /api/bank-info/all/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Travel-Booking-Framework\ProfilesService\Profile\api\views.py", line 97, in get
    bank_infos = UserBankInfoService.get_all_bank_infos()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserBankInfoService.get_all_bank_infos() missing 1 required positional argument: 'user_bank_info'
[2025-02-01 12:55:16] ERROR django.server "GET /api/bank-info/all/ HTTP/1.1" 500 22503
[2025-02-01 12:55:41] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 12:55:44] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 12:55:44] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 12:55:44] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 12:55:48] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 12:55:48] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3767
[2025-02-01 12:55:55] ERROR django.request Internal Server Error: /api/bank-info/all/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'card_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Travel-Booking-Framework\ProfilesService\Profile\api\views.py", line 99, in get
    return Response(serializer.data, status=status.HTTP_200_OK)
                    ^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `card_number` on serializer `UserBankInfoSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'card_number'.
[2025-02-01 12:55:55] ERROR django.server "GET /api/bank-info/all/ HTTP/1.1" 500 24840
[2025-02-01 13:33:38] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 13:33:42] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 13:33:42] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 13:33:42] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 13:33:42] WARNING django.request Not Found: /favicon.ico
[2025-02-01 13:33:42] WARNING django.server "GET /favicon.ico HTTP/1.1" 404 3039
[2025-02-01 13:33:50] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 13:33:50] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3767
[2025-02-01 13:34:02] WARNING django.request Bad Request: /api/user-bank-info/
[2025-02-01 13:34:02] WARNING django.server "POST /api/user-bank-info/ HTTP/1.1" 400 100
[2025-02-01 13:34:18] ERROR django.request Internal Server Error: /api/user-bank-info/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UserBankInfoView.put() missing 1 required positional argument: 'pk'
[2025-02-01 13:34:18] ERROR django.server "PUT /api/user-bank-info/ HTTP/1.1" 500 22282
[2025-02-01 13:36:24] ERROR django.request Internal Server Error: /api/bank-info/all/
Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 437, in get_attribute
    return get_attribute(instance, self.source_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 104, in get_attribute
    instance = getattr(instance, attr)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'card_number'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Travel-Booking-Framework\ProfilesService\Profile\api\views.py", line 99, in get
    return Response(serializer.data, status=status.HTTP_200_OK)
                    ^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 713, in to_representation
    return [
           ^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 714, in <listcomp>
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\serializers.py", line 525, in to_representation
    attribute = field.get_attribute(instance)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Master Terms\Term 1\Final-Project-Distributed-System\ProfilesService\Lib\site-packages\rest_framework\fields.py", line 470, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `card_number` on serializer `UserBankInfoSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `str` instance.
Original exception text was: 'str' object has no attribute 'card_number'.
[2025-02-01 13:36:24] ERROR django.server "GET /api/bank-info/all/ HTTP/1.1" 500 24840
[2025-02-01 13:42:09] INFO django.utils.autoreload Watching for file changes with StatReloader
[2025-02-01 13:42:11] INFO django.server "GET / HTTP/1.1" 302 0
[2025-02-01 13:42:11] INFO django.server "GET /admin/ HTTP/1.1" 302 0
[2025-02-01 13:42:11] INFO django.server "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3818
[2025-02-01 13:42:18] INFO django.server "GET /swagger/ HTTP/1.1" 200 2215
[2025-02-01 13:42:18] INFO django.server "GET /swagger/?format=openapi HTTP/1.1" 200 3767
[2025-02-01 13:42:26] INFO django.server "GET /api/bank-info/all/ HTTP/1.1" 200 2
